import { defaultSchema, type Schema } from "hast-util-sanitize";

// Sanitize schema for *author-derived* markup only. Everything generated by
// the pipeline (KaTeX, Shiki, Mermaid SVG, heading anchors, external-link
// attrs) is injected after this step and never passes through it.
export const sanitizeSchema: Schema = {
  ...defaultSchema,
  // mdast-util-to-hast already emits user-content-* footnote ids; clobbering
  // them again would desync the fnref <-> fn links. `name` keeps its
  // clobbering since footnotes use `id`, not `name`.
  clobber: ["name"],
  tagNames: [...(defaultSchema.tagNames ?? []), "svg", "path"],
  attributes: {
    ...defaultSchema.attributes,
    // defaultSchema allows `id` on every element. Restrict it to the
    // generated user-content-* prefix plus the footnote label (refs point
    // aria-describedby at it): a raw-HTML `id` could otherwise clobber
    // landmarks (#main) or footnote anchors. Only the first definition
    // per attribute name is consulted, so both values share one tuple.
    // Heading ids are added by rehype-slug after this step and are
    // unaffected.
    "*": [
      ...(defaultSchema.attributes?.["*"] ?? []).filter((attr) => !(typeof attr === "string" && attr === "id")),
      ["id", /^user-content-/, "footnote-label"],
    ],
    div: [...(defaultSchema.attributes?.div ?? []), ["className", /^markdown-alert/]],
    p: [...(defaultSchema.attributes?.p ?? []), ["className", "markdown-alert-title"]],
    // loading/decoding are performance hints, not attack surface — allow
    // author overrides (rehypeResolveImages only fills unset values).
    img: [...(defaultSchema.attributes?.img ?? []), "loading", "decoding"],
    section: [...(defaultSchema.attributes?.section ?? []), "ariaLabelledBy"],
    svg: [["className", "octicon"], "viewBox", "width", "height", "ariaHidden"],
    path: ["d"],
  },
};
