import { transformerNotationDiff, transformerNotationHighlight } from "@shikijs/transformers";
import rehypeShiki from "@shikijs/rehype";
import matter from "gray-matter";
import type { Element, ElementContent, Parent, Root } from "hast";
import { CORE_SCHEMA, load } from "js-yaml";
import { fromHtml } from "hast-util-from-html";
import { defaultSchema, type Schema } from "hast-util-sanitize";
import { toText } from "hast-util-to-text";
import type { Html, Image, Parents, Root as MdastRoot } from "mdast";
import rehypeExternalLinks from "rehype-external-links";
import rehypeKatex from "rehype-katex";
import rehypeSanitize from "rehype-sanitize";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import { remarkAlert } from "remark-github-blockquote-alert";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified, type Plugin } from "unified";
import { SKIP, visit } from "unist-util-visit";
import { z } from "zod";
import { parseDate } from "$lib/date";
import type { TocItem } from "$lib/types";
import { renderMermaid } from "./mermaid";

// gray-matter's bundled js-yaml resolves YAML timestamps into Date objects
// (UTC for date-only, machine-local otherwise) — parsing with CORE_SCHEMA
// keeps them as strings so parseDate can pin bare dates to JST instead.
const matterOptions = {
  engines: {
    yaml: {
      parse: (input: string) => load(input, { schema: CORE_SCHEMA }) as Record<string, unknown>,
      stringify: (data: unknown) => String(data),
    },
  },
};

const frontmatterDate = z.string().transform((value, ctx) => {
  const timestamp = parseDate(value);
  if (Number.isNaN(timestamp)) {
    ctx.addIssue({ code: "custom", message: `invalid date: ${JSON.stringify(value)}` });
    return z.NEVER;
  }
  return new Date(timestamp);
});

const postFrontmatter = z.object({
  title: z.string(),
  description: z.string().default(""),
  publishedAt: frontmatterDate,
  updatedAt: frontmatterDate.optional(),
  tags: z.array(z.string()).default([]),
  series: z.string().optional(),
  draft: z.boolean().default(false),
});

export type { TocItem };

export interface Post {
  slug: string;
  title: string;
  description: string;
  publishedAt: Date;
  updatedAt: Date | null;
  tags: string[];
  series: string | null;
  html: string;
  toc: TocItem[];
  readingTime: number;
}

// Posts live at content/posts/<year>/<slug>/index.md — the year folder is
// organizational only (the URL stays /posts/<slug>/).
const postFiles = import.meta.glob<string>("/content/posts/*/*/index.md", {
  query: "?raw",
  import: "default",
  eager: true,
});

// Assets co-located with a post (images etc.) are bundled by vite; markdown
// references them relatively (./image.png) and remarkResolveImages swaps in
// the emitted URL.
const postAssets = import.meta.glob<string>("/content/posts/*/**/*.{png,jpg,jpeg,gif,svg,webp,avif}", {
  query: "?url",
  import: "default",
  eager: true,
});

// Sanitize schema for *author-derived* markup only. Everything generated by
// the pipeline (KaTeX, Shiki, Mermaid SVG, heading anchors, external-link
// attrs) is injected after this step and never passes through it.
const schema: Schema = {
  ...defaultSchema,
  // mdast-util-to-hast already emits user-content-* footnote ids; clobbering
  // them again would desync the fnref <-> fn links.
  clobber: [],
  tagNames: [...(defaultSchema.tagNames ?? []), "svg", "path"],
  attributes: {
    ...defaultSchema.attributes,
    div: [...(defaultSchema.attributes?.div ?? []), ["className", /^markdown-alert/]],
    p: [...(defaultSchema.attributes?.p ?? []), ["className", "markdown-alert-title"]],
    section: [...(defaultSchema.attributes?.section ?? []), "ariaLabelledBy"],
    svg: [["className", "octicon"], "viewBox", "width", "height", "ariaHidden"],
    path: ["d"],
  },
};

// Raw HTML in markdown source is escaped into literal text (Hugo-style):
// generated markup is added later as hast nodes, not HTML strings.
const remarkTextifyHtml: Plugin<[], MdastRoot> = () => (tree) => {
  visit(tree, "html", (node: Html, index: number | undefined, parent: Parents | undefined) => {
    if (parent && index !== undefined) {
      parent.children[index] = { type: "text", value: node.value };
    }
  });
};

// Relative image srcs resolve against the post's own directory via the
// bundled-asset map, so each post folder is self-contained.
const remarkResolveImages =
  (resolveImage: (src: string) => string): Plugin<[], MdastRoot> =>
  () =>
  (tree) => {
    visit(tree, "image", (node: Image) => {
      node.url = resolveImage(node.url);
    });
  };

// ```mermaid blocks -> light/dark SVGs. Runs before shiki so the block is
// replaced rather than syntax-highlighted.
const rehypeMermaid: Plugin<[], Root> = () => async (tree) => {
  const blocks: { parent: Parent; index: number; source: string }[] = [];
  visit(tree, "element", (node, index, parent) => {
    if (node.tagName !== "pre" || index === undefined || parent === undefined) return;
    const code = node.children[0];
    if (code?.type !== "element" || code.tagName !== "code") return;
    const classes = code.properties?.className;
    if (!Array.isArray(classes) || !classes.includes("language-mermaid")) return;
    // whitespace:"pre" keeps newlines — the default "normal" collapses them
    // like CSS, handing mermaid a single-line source that fails to parse.
    blocks.push({ parent, index, source: toText(code, { whitespace: "pre" }) });
  });
  /* oxlint-disable no-await-in-loop -- renderMermaid serializes work internally; one queue, sequential calls */
  for (const block of blocks) {
    const rendered = await renderMermaid(block.source);
    if (!rendered) continue; // stays a code block — shiki renders it as a fallback
    const fragment = fromHtml(
      `<div class="mermaid-diagram mermaid-light">${rendered.light}</div><div class="mermaid-diagram mermaid-dark">${rendered.dark}</div>`,
      { fragment: true },
    );
    block.parent.children[block.index] = {
      type: "element",
      tagName: "div",
      properties: {},
      children: fragment.children.filter((child): child is ElementContent => child.type !== "doctype"),
    };
  }
  /* oxlint-enable no-await-in-loop */
};

// Screen-reader-only headings (the footnotes section label) get ids but are
// not real content headings — exclude them from toc and permalink anchors.
const isContentHeading = (node: Element): boolean =>
  /^h[1-6]$/.test(node.tagName) && !(node.properties?.className as string[] | undefined)?.includes("sr-only");

// Collects headings after rehype-slug assigns ids. Must run before
// rehypeHeadingAnchors, which would add the "#" anchor to the text.
const rehypeCollectToc: Plugin<[], Root> = () => (tree, file) => {
  const toc: TocItem[] = [];
  visit(tree, "element", (node) => {
    const id = node.properties?.id;
    if (isContentHeading(node) && typeof id === "string") {
      toc.push({ id, text: toText(node).trim(), depth: Number(node.tagName[1]) });
    }
  });
  file.data.toc = toc;
};

// Appends a keyboard-focusable "#" permalink to each content heading.
const rehypeHeadingAnchors: Plugin<[], Root> = () => (tree) => {
  visit(tree, "element", (node) => {
    const id = node.properties?.id;
    if (!isContentHeading(node) || typeof id !== "string" || node.tagName === "h1") return;
    node.children.push({
      type: "element",
      tagName: "a",
      properties: {
        className: ["heading-anchor"],
        href: `#${id}`,
        ariaLabel: `${toText(node).trim()} へのリンク`,
      },
      children: [{ type: "text", value: "#" }],
    });
  });
};

const rehypeLazyImages: Plugin<[], Root> = () => (tree) => {
  visit(tree, "element", (node) => {
    if (node.tagName === "img") node.properties.loading = "lazy";
  });
};

// Collects the text a reader actually reads, for reading-time estimation.
// Runs on the final tree so generated noise is excluded: code blocks,
// rendered math, heading permalinks, and diagram SVGs. This replaces the
// old approach of stripping the same constructs from raw markdown by regex
// (which also miscounted image/link URLs as text).
const rehypeCollectReadingText: Plugin<[], Root> = () => (tree, file) => {
  const parts: string[] = [];
  visit(tree, (node) => {
    if (node.type === "element") {
      const classes = node.properties?.className;
      const skipClass =
        Array.isArray(classes) &&
        (classes.includes("katex") || classes.includes("heading-anchor") || classes.includes("footnotes"));
      if (node.tagName === "pre" || node.tagName === "svg" || skipClass) return SKIP;
    }
    if (node.type === "text") parts.push(node.value);
  });
  file.data.readingText = parts.join(" ");
};

const createProcessor = (resolveImage: (src: string) => string) =>
  unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkMath)
    .use(remarkTextifyHtml)
    .use(remarkAlert)
    .use(remarkResolveImages(resolveImage))
    .use(remarkRehype)
    // Trust boundary: author-derived markup is sanitized here; everything
    // below only adds generated markup on top of the sanitized tree.
    .use(rehypeSanitize, schema)
    .use(rehypeSlug)
    .use(rehypeCollectToc)
    .use(rehypeHeadingAnchors)
    .use(rehypeExternalLinks, { target: "_blank", rel: ["noopener", "noreferrer"] })
    .use(rehypeMermaid)
    .use(rehypeShiki, {
      themes: { light: "github-light", dark: "github-dark" },
      defaultColor: "light-dark()",
      cssVariablePrefix: "--shiki-",
      transformers: [transformerNotationHighlight(), transformerNotationDiff()],
    })
    .use(rehypeKatex)
    .use(rehypeLazyImages)
    .use(rehypeCollectReadingText)
    .use(rehypeStringify);

export async function renderMarkdown(
  content: string,
  options: { resolveImage?: (src: string) => string } = {},
): Promise<{ html: string; toc: TocItem[]; plainText: string }> {
  const file = await createProcessor(options.resolveImage ?? ((src) => src)).process(content);
  return {
    html: String(file),
    toc: (file.data.toc as TocItem[] | undefined) ?? [],
    plainText: (file.data.readingText as string | undefined) ?? "",
  };
}

// Rough bilingual heuristic: ~400 wpm for space-delimited text, ~800
// chars/min for Japanese (which has no spaces). Whichever is larger wins.
function estimateReadingTime(plainText: string): number {
  const words = plainText.trim().split(/\s+/).filter(Boolean).length;
  const chars = plainText.replace(/\s/g, "").length;
  return Math.max(1, Math.ceil(Math.max(words / 400, chars / 800)));
}

let cache: Promise<Post[]> | null = null;

export function getPosts(): Promise<Post[]> {
  return (cache ??= loadPosts().catch((error) => {
    // A rejected cache would poison every subsequent call — reset on failure.
    cache = null;
    throw error;
  }));
}

async function loadPosts(): Promise<Post[]> {
  return loadPostsFrom(postFiles, postAssets);
}

// Files/assets are injectable so tests can exercise the loading rules
// (skip/dedup/draft/date parsing) without fixtures in content/.
export async function loadPostsFrom(files: Record<string, string>, assets: Record<string, string>): Promise<Post[]> {
  const slugs = new Set<string>();
  const posts = await Promise.all(
    Object.entries(files).map(async ([path, raw]): Promise<Post | null> => {
      // matter() throws YAMLException on malformed frontmatter — a single
      // bad file must not fail the whole build.
      let matterResult: ReturnType<typeof matter>;
      try {
        matterResult = matter(raw, matterOptions);
      } catch (error) {
        console.warn(`[posts] skipping ${path}: frontmatter parse failed`, error);
        return null;
      }
      const { data, content } = matterResult;
      const parsed = postFrontmatter.safeParse(data);
      if (!parsed.success) {
        console.warn(`[posts] skipping ${path}:`, parsed.error.issues);
        return null;
      }
      const fm = parsed.data;
      if (fm.draft) return null;
      // /content/posts/<year>/<slug>/index.md — slug is the folder name and
      // must be unique since it is the URL segment.
      const dir = path.slice(0, path.lastIndexOf("/"));
      const slug = dir.split("/").pop() ?? "";
      if (!slug || slugs.has(slug)) {
        console.warn(`[posts] skipping ${path}: duplicate or missing slug "${slug}"`);
        return null;
      }
      slugs.add(slug);
      const resolveImage = (src: string): string => {
        // Absolute URLs, site-root paths, and anchors pass through untouched.
        if (/^[a-z]+:/i.test(src) || src.startsWith("/") || src.startsWith("#")) return src;
        const bundled = assets[`${dir}/${src.replace(/^\.\//, "")}`];
        if (!bundled) {
          console.warn(`[posts] ${path}: image "${src}" not found beside the post`);
          return src;
        }
        return bundled;
      };
      const { html, toc, plainText } = await renderMarkdown(content, { resolveImage });
      return {
        slug,
        title: fm.title,
        description: fm.description,
        publishedAt: fm.publishedAt,
        updatedAt: fm.updatedAt ?? null,
        tags: fm.tags,
        series: fm.series ?? null,
        html,
        toc,
        readingTime: estimateReadingTime(plainText),
      };
    }),
  );
  return posts
    .filter((post): post is Post => post !== null)
    .toSorted((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime());
}
