import { transformerNotationDiff, transformerNotationHighlight } from "@shikijs/transformers";
import rehypeShiki from "@shikijs/rehype";
import matter from "gray-matter";
import type { Element, ElementContent, Parent, Root } from "hast";
import { fromHtml } from "hast-util-from-html";
import { defaultSchema, type Schema } from "hast-util-sanitize";
import { toText } from "hast-util-to-text";
import type { Html, Parents, Root as MdastRoot } from "mdast";
import rehypeExternalLinks from "rehype-external-links";
import rehypeKatex from "rehype-katex";
import rehypeSanitize from "rehype-sanitize";
import rehypeSlug from "rehype-slug";
import rehypeStringify from "rehype-stringify";
import { remarkAlert } from "remark-github-blockquote-alert";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified, type Plugin } from "unified";
import { visit } from "unist-util-visit";
import { z } from "zod";
import type { TocItem } from "$lib/types";
import { renderMermaid } from "./mermaid";

const postFrontmatter = z.object({
  title: z.string(),
  description: z.string().default(""),
  publishedAt: z.coerce.date(),
  updatedAt: z.coerce.date().optional(),
  tags: z.array(z.string()).default([]),
  series: z.string().optional(),
  draft: z.boolean().default(false),
});

export type { TocItem };

export interface Post {
  slug: string;
  title: string;
  description: string;
  publishedAt: Date;
  updatedAt: Date | null;
  tags: string[];
  series: string | null;
  html: string;
  toc: TocItem[];
  readingTime: number;
}

const postFiles = import.meta.glob<string>("/content/posts/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
});

// Sanitize schema for *author-derived* markup only. Everything generated by
// the pipeline (KaTeX, Shiki, Mermaid SVG, heading anchors, external-link
// attrs) is injected after this step and never passes through it.
const schema: Schema = {
  ...defaultSchema,
  // mdast-util-to-hast already emits user-content-* footnote ids; clobbering
  // them again would desync the fnref <-> fn links.
  clobber: [],
  tagNames: [...(defaultSchema.tagNames ?? []), "svg", "path"],
  attributes: {
    ...defaultSchema.attributes,
    div: [...(defaultSchema.attributes?.div ?? []), ["className", /^markdown-alert/]],
    p: [...(defaultSchema.attributes?.p ?? []), ["className", "markdown-alert-title"]],
    section: [...(defaultSchema.attributes?.section ?? []), "ariaLabelledBy"],
    svg: [["className", "octicon"], "viewBox", "width", "height", "ariaHidden"],
    path: ["d"],
  },
};

// Raw HTML in markdown source is escaped into literal text (Hugo-style):
// generated markup is added later as hast nodes, not HTML strings.
const remarkTextifyHtml: Plugin<[], MdastRoot> = () => (tree) => {
  visit(tree, "html", (node: Html, index: number | undefined, parent: Parents | undefined) => {
    if (parent && index !== undefined) {
      parent.children[index] = { type: "text", value: node.value };
    }
  });
};

// ```mermaid blocks -> light/dark SVGs. Runs before shiki so the block is
// replaced rather than syntax-highlighted.
const rehypeMermaid: Plugin<[], Root> = () => async (tree) => {
  const blocks: { parent: Parent; index: number; source: string }[] = [];
  visit(tree, "element", (node, index, parent) => {
    if (node.tagName !== "pre" || index === undefined || parent === undefined) return;
    const code = node.children[0];
    if (code?.type !== "element" || code.tagName !== "code") return;
    const classes = code.properties?.className;
    if (!Array.isArray(classes) || !classes.includes("language-mermaid")) return;
    blocks.push({ parent, index, source: toText(code) });
  });
  /* oxlint-disable no-await-in-loop -- renderMermaid serializes work internally; one queue, sequential calls */
  for (const block of blocks) {
    const rendered = await renderMermaid(block.source);
    if (!rendered) continue; // stays a code block — shiki renders it as a fallback
    const fragment = fromHtml(
      `<div class="mermaid-diagram mermaid-light">${rendered.light}</div><div class="mermaid-diagram mermaid-dark">${rendered.dark}</div>`,
      { fragment: true },
    );
    block.parent.children[block.index] = {
      type: "element",
      tagName: "div",
      properties: {},
      children: fragment.children.filter((child): child is ElementContent => child.type !== "doctype"),
    };
  }
  /* oxlint-enable no-await-in-loop */
};

// Screen-reader-only headings (the footnotes section label) get ids but are
// not real content headings — exclude them from toc and permalink anchors.
const isContentHeading = (node: Element): boolean =>
  /^h[1-6]$/.test(node.tagName) && !(node.properties?.className as string[] | undefined)?.includes("sr-only");

// Collects headings after rehype-slug assigns ids. Must run before
// rehypeHeadingAnchors, which would add the "#" anchor to the text.
const rehypeCollectToc: Plugin<[], Root> = () => (tree, file) => {
  const toc: TocItem[] = [];
  visit(tree, "element", (node) => {
    const id = node.properties?.id;
    if (isContentHeading(node) && typeof id === "string") {
      toc.push({ id, text: toText(node).trim(), depth: Number(node.tagName[1]) });
    }
  });
  file.data.toc = toc;
};

// Appends a keyboard-focusable "#" permalink to each content heading.
const rehypeHeadingAnchors: Plugin<[], Root> = () => (tree) => {
  visit(tree, "element", (node) => {
    const id = node.properties?.id;
    if (!isContentHeading(node) || typeof id !== "string" || node.tagName === "h1") return;
    node.children.push({
      type: "element",
      tagName: "a",
      properties: {
        className: ["heading-anchor"],
        href: `#${id}`,
        ariaLabel: `${toText(node).trim()} へのリンク`,
      },
      children: [{ type: "text", value: "#" }],
    });
  });
};

const rehypeLazyImages: Plugin<[], Root> = () => (tree) => {
  visit(tree, "element", (node) => {
    if (node.tagName === "img") node.properties.loading = "lazy";
  });
};

const processor = unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkMath)
  .use(remarkTextifyHtml)
  .use(remarkAlert)
  .use(remarkRehype)
  // Trust boundary: author-derived markup is sanitized here; everything
  // below only adds generated markup on top of the sanitized tree.
  .use(rehypeSanitize, schema)
  .use(rehypeSlug)
  .use(rehypeCollectToc)
  .use(rehypeHeadingAnchors)
  .use(rehypeExternalLinks, { target: "_blank", rel: ["noopener", "noreferrer"] })
  .use(rehypeMermaid)
  .use(rehypeShiki, {
    themes: { light: "github-light", dark: "github-dark" },
    defaultColor: "light-dark()",
    cssVariablePrefix: "--shiki-",
    transformers: [transformerNotationHighlight(), transformerNotationDiff()],
  })
  .use(rehypeKatex)
  .use(rehypeLazyImages)
  .use(rehypeStringify);

export async function renderMarkdown(content: string): Promise<{ html: string; toc: TocItem[] }> {
  const file = await processor.process(content);
  return { html: String(file), toc: (file.data.toc as TocItem[] | undefined) ?? [] };
}

function estimateReadingTime(content: string): number {
  const plain = content
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/\$\$[\s\S]*?\$\$|\$[^$\n]+\$/g, " ")
    .replace(/[#*_`>|[\]()-]/g, " ");
  const words = plain.trim().split(/\s+/).filter(Boolean).length;
  const chars = plain.replace(/\s/g, "").length;
  const minutes = Math.max(words / 400, chars / 800);
  return Math.max(1, Math.ceil(minutes));
}

let cache: Promise<Post[]> | null = null;

export function getPosts(): Promise<Post[]> {
  return (cache ??= loadPosts().catch((error) => {
    // A rejected cache would poison every subsequent call — reset on failure.
    cache = null;
    throw error;
  }));
}

async function loadPosts(): Promise<Post[]> {
  const posts = await Promise.all(
    Object.entries(postFiles).map(async ([path, raw]): Promise<Post | null> => {
      // matter() throws YAMLException on malformed frontmatter — a single
      // bad file must not fail the whole build.
      let matterResult: ReturnType<typeof matter>;
      try {
        matterResult = matter(raw);
      } catch (error) {
        console.warn(`[posts] skipping ${path}: frontmatter parse failed`, error);
        return null;
      }
      const { data, content } = matterResult;
      const parsed = postFrontmatter.safeParse(data);
      if (!parsed.success) {
        console.warn(`[posts] skipping ${path}:`, parsed.error.issues);
        return null;
      }
      const fm = parsed.data;
      if (fm.draft) return null;
      const { html, toc } = await renderMarkdown(content);
      return {
        slug: path.split("/").pop()?.replace(/\.md$/, "") ?? "",
        title: fm.title,
        description: fm.description,
        publishedAt: fm.publishedAt,
        updatedAt: fm.updatedAt ?? null,
        tags: fm.tags,
        series: fm.series ?? null,
        html,
        toc,
        readingTime: estimateReadingTime(content),
      };
    }),
  );
  return posts
    .filter((post): post is Post => post !== null)
    .toSorted((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime());
}
