<script lang="ts">
  import { onMount } from "svelte";
  import { replaceState } from "$app/navigation";
  import { page } from "$app/state";
  import LangText from "$lib/components/LangText.svelte";

  interface PagefindResult {
    url: string;
    meta: { title?: string };
    excerpt: string;
  }
  interface PagefindSearch {
    results: { data: () => Promise<PagefindResult> }[];
  }
  interface PagefindApi {
    init: () => Promise<void>;
    debouncedSearch: (
      query: string,
      options?: Record<string, unknown>,
      duration?: number,
    ) => Promise<PagefindSearch | null>;
  }

  let query = $state("");
  let results = $state<PagefindResult[]>([]);
  let searching = $state(false);
  let pagefind: PagefindApi | null = null;
  const inputLabelId = $props.id();
  // Render the (disabled) input during SSR so hydration doesn't shift layout;
  // the whole block hides only when pagefind is actually absent.
  let status = $state<"loading" | "ready" | "unavailable">("loading");

  onMount(async () => {
    try {
      // generated by pagefind at build time — absent in dev mode
      const pagefindUrl = "/pagefind/pagefind.js";
      pagefind = (await import(/* @vite-ignore */ pagefindUrl)) as PagefindApi;
      await pagefind.init();
      status = "ready";
      // A ?q= applied before init skipped the search — run it now.
      if (query.trim()) void onInput();
    } catch {
      status = "unavailable";
    }
  });

  // ?q= can also change via SPA navigation after mount (shared search links).
  // Compare against the trimmed query so a trailing space being typed isn't
  // eaten by our own replaceState round-trip.
  $effect(() => {
    const q = page.url.searchParams.get("q");
    if (q && q !== query.trim()) {
      query = q;
      void onInput();
    }
  });

  async function onInput() {
    const url = new URL(page.url);
    if (query.trim()) url.searchParams.set("q", query.trim());
    else url.searchParams.delete("q");
    // SvelteKit's replaceState preserves router state; raw history.replaceState
    // would clobber the nav index/scroll state it stores in history.state.
    replaceState(url, page.state);
    if (!pagefind) return;
    if (!query.trim()) {
      results = [];
      searching = false;
      return;
    }
    searching = true;
    const res = await pagefind.debouncedSearch(query, {}, 300);
    // null when superseded by a newer keystroke — that call owns the flag
    if (!res) return;
    // /og/ pages are build-time templates for OG image generation, not content
    const hits = res.results.slice(0, 12).map((r) => r.data());
    results = (await Promise.all(hits)).filter((r) => !r.url.includes("/og/")).slice(0, 8);
    searching = false;
  }
</script>

{#if status !== "unavailable"}
  <search class="flex flex-col gap-3">
    <input
      type="search"
      bind:value={query}
      oninput={onInput}
      disabled={status !== "ready"}
      class="border-border bg-surface w-full rounded-md border px-3 py-2 text-sm disabled:opacity-60"
      placeholder="記事を検索 / Search"
      aria-labelledby={inputLabelId}
    />
    <span id={inputLabelId} class="sr-only"><LangText texts={{ ja: "記事を検索", en: "Search" }} /></span>
    {#if results.length > 0}
      <ul class="flex flex-col gap-2" aria-live="polite">
        {#each results as result (result.url)}
          <li>
            <a href={result.url} class="text-foreground text-sm font-medium hover:underline">
              {result.meta.title ?? result.url}
            </a>
            <p class="text-muted line-clamp-2 text-xs">{@html result.excerpt}</p>
          </li>
        {/each}
      </ul>
    {:else if query.trim() && !searching}
      <p class="text-muted text-sm">
        <LangText texts={{ ja: "見つかりませんでした", en: "No results" }} />
      </p>
    {/if}
  </search>
{/if}
