<script lang="ts">
  import { onMount } from "svelte";
  import LangText from "$lib/components/LangText.svelte";

  interface PagefindResult {
    url: string;
    meta: { title?: string };
    excerpt: string;
  }
  interface PagefindSearch {
    results: { data: () => Promise<PagefindResult> }[];
  }
  interface PagefindApi {
    init: () => Promise<void>;
    debouncedSearch: (query: string, options?: object, duration?: number) => Promise<PagefindSearch | null>;
  }

  let query = $state("");
  let results = $state<PagefindResult[]>([]);
  let searching = $state(false);
  let pagefind: PagefindApi | null = null;
  let available = $state(false);

  onMount(async () => {
    try {
      // generated by pagefind at build time — absent in dev mode
      const pagefindUrl = "/pagefind/pagefind.js";
      pagefind = (await import(/* @vite-ignore */ pagefindUrl)) as PagefindApi;
      await pagefind.init();
      available = true;
      const initial = new URLSearchParams(window.location.search).get("q");
      if (initial) {
        query = initial;
        onInput();
      }
    } catch {
      available = false;
    }
  });

  async function onInput() {
    const url = new URL(window.location.href);
    if (query.trim()) url.searchParams.set("q", query.trim());
    else url.searchParams.delete("q");
    window.history.replaceState(null, "", url);
    if (!pagefind) return;
    if (!query.trim()) {
      results = [];
      searching = false;
      return;
    }
    searching = true;
    const res = await pagefind.debouncedSearch(query, {}, 300);
    // null when superseded by a newer keystroke — that call owns the flag
    if (!res) {
      searching = false;
      return;
    }
    // /og/ pages are build-time templates for OG image generation, not content
    const hits = res.results.slice(0, 12).map((r) => r.data());
    results = (await Promise.all(hits)).filter((r) => !r.url.includes("/og/")).slice(0, 8);
    searching = false;
  }
</script>

{#if available}
  <search class="flex flex-col gap-3">
    <input
      type="search"
      bind:value={query}
      oninput={onInput}
      class="border-border bg-surface w-full rounded-md border px-3 py-2 text-sm"
      placeholder="記事を検索 / Search"
      aria-label="記事を検索 / Search"
    />
    <span class="sr-only"><LangText texts={{ ja: "記事を検索", en: "Search" }} /></span>
    {#if results.length > 0}
      <ul class="flex flex-col gap-2" aria-live="polite">
        {#each results as result (result.url)}
          <li>
            <a href={result.url} class="text-foreground text-sm font-medium hover:underline">
              {result.meta.title ?? result.url}
            </a>
            <p class="text-muted line-clamp-2 text-xs">{@html result.excerpt}</p>
          </li>
        {/each}
      </ul>
    {:else if query.trim() && !searching}
      <p class="text-muted text-sm">
        <LangText texts={{ ja: "見つかりませんでした", en: "No results" }} />
      </p>
    {/if}
  </search>
{/if}
